### ISSUE TITLE
iOS Phonegap Origin Request Header crashes zf2...

### ISSUE THREAD

**Issue by basz** [zf-fr/zfr-cors#18]
I'm not sure if I am at the correct place - my understanding of this whole CORS is quite limited as I am starting out with this, but I thought you might have some insights in this.

But let me explain - I appreciate your advice. I have an phonegap application written with emberjs and https://github.com/simplabs/ember-simple-auth.

Everything works correctly when I run this project in the browser on my Mac. Whenever I create it into an iOS app (thus running as phonegap application) the Origin header is specified as 'file://'. This is a problem as this line https://github.com/zf-fr/zfr-cors/blob/master/src/ZfrCors/Service/CorsService.php#L65 will throw an exception because file:// wil not parse as a valid url.

I validated this issue by doing the following. Now my result will pass. I know this is not really secure and that any further (defined after the Origin) headers are not lazy loaded and thus not available in the header object.
```
        try {
            $originUri = UriFactory::factory($headers->get('Origin')->getFieldValue());
        } catch (InvalidArgumentException $e) {
            return true;
        }
```
Alternatively I tried to set the Origin header via jQuery.
```
      jqXHR.setRequestHeader("Origin", "https://app.example.com");
```
However this throws an in browser error as the Origin header is restricted to be modified.
```
[Error] Refused to set unsafe header "Origin"
	setRequestHeader ([native code], line 0)
	send (jquery-1.10.2.min.js, line 25)
	ajax (jquery-1.10.2.min.js, line 25)
	login (ember-simple-auth.js, line 460)
	send (ember-1.1.2.js, line 14740)
	submit (app-user.min.js, line 1)
	send (ember-1.1.2.js, line 14740)
	(anonymous function) (ember-1.1.2.js, line 33233)
	run (ember-1.1.2.js, line 5609)
	run (ember-1.1.2.js, line 5974)
	handler (ember-1.1.2.js, line 33231)
	(anonymous function) (ember-fastclick.js, line 126)
	dispatch (jquery-1.10.2.min.js, line 25)
	handle (jquery-1.10.2.min.js, line 25)
```

**Comment by fabiopaiva** [comment]
The uri "file://" return a invalid uri, then my solution was:

    public function onBootstrap(MvcEvent $e)
    {
        $eventManager        = $e->getApplication()->getEventManager();
        $headers = $e->getRequest()->getHeaders();
        if ($headers->has('Origin')) {
            //convert to array because get method throw an exception
            $headersArray = $headers->toArray();
            $origin = $headersArray['Origin'];
            if ($origin === 'file://') {
                unset($headersArray['Origin']);
                $headers->clearHeaders();
                $headers->addHeaders($headersArray);
                //this is a valid uri
                $headers->addHeaderLine('Origin', 'file://mobile');
            }
        }
    }

in zfr-cors.local.php add

    return array(
        'zfr_cors' => array(
         /**
          * Set the list of allowed origins domain with protocol.
          */
        'allowed_origins' => array(
            'file://mobile',
        )
        //...//
    );

**Comment by fabiopaiva** [comment]
Same above with double check

    public function onBootstrap(MvcEvent $e)
    {
        $eventManager        = $e->getApplication()->getEventManager();
        $headers = $e->getRequest()->getHeaders();
        if ($headers->has('Origin') &&
            $headers->has('X-Requested-With') &&
            $headers->get('X-Requested-With')->getFieldValue() === 'com.domainname.mycordovapackagename') {
            //convert to array because get method throw an exception
            $headersArray = $headers->toArray();
            $origin = $headersArray['Origin'];
            if ($origin === 'file://') {
                unset($headersArray['Origin']);
                $headers->clearHeaders();
                $headers->addHeaders($headersArray);
                //this is a valid uri
                $headers->addHeaderLine('Origin', 'file://mobile');
            }
        }
    }

in zfr-cors.local.php add

    return array(
        'zfr_cors' => array(
         /**
          * Set the list of allowed origins domain with protocol.
          */
        'allowed_origins' => array(
            'file://mobile',
        )
        //...//
    );

**Comment by solcre** [comment]
This is issue is so old, what are the plans for this problem ?

**Comment by fabiopaiva** [comment]
@solcre the problem isn't in zfr-cors

**Comment by fabiopaiva** [comment]
Imho this issue must be closed.
