### ISSUE TITLE
zfr-cors is not working in cordova

### ISSUE THREAD

**Issue by sohailyasmin** [zf-fr/zfr-cors#29]
I am facing this issue when i send ajax call from mobile app using cordova, i have found many other people are facing same issue 

this is error 
-----------------------
I/chromium( 2589): <b>Fatal error</b>:  Uncaught exception 'Zend\Http\Header\Exc
eption\InvalidArgumentException' with message 'Invalid header value for Origin k
ey: &quot;Origin&quot;' in /var/www/html/stgapi/vendor/zendframework/zendframewo
rk/library/Zend/Http/Header/Origin.php:36

I/chromium( 2589): Stack trace:

I/chromium( 2589): #0 /var/www/html/stgapi/vendor/zendframework/zendframework/li
brary/Zend/Http/Headers.php(432): Zend\Http\Header\Origin::fromString('Origin: f
ile://')

I/chromium( 2589): #1 /var/www/html/stgapi/vendor/zendframework/zendframework/li
brary/Zend/Http/Headers.php(271): Zend\Http\Headers-&gt;lazyLoadHeader(5)

I/chromium( 2589): #2 /var/www/html/stgapi/vendor/zfr/zfr-cors/src/ZfrCors/Servi
ce/CorsService.php(65): Zend\Http\Headers-&gt;get('Origin')

I/chromium( 2589): #3 /var/www/html/stgapi/vendor/zfr/zfr-cors/src/ZfrCors/Mvc/C
orsRequestListener.php(83): ZfrCors\Service\CorsService-&gt;isCorsRequest(Object
(ZF\ContentNegotiation\Request))

I/chromium( 2589): #4 [internal function]: ZfrCors\Mvc\CorsRequestListener-&gt;o
nCorsPreflight(Object(Zend\Mvc\MvcEvent))

I/chromium( 2589): #5 /var/www/html/stgapi/vendor/zendframework/zendframework/li
brary/Zend/EventManager/EventManager.php(468):  in <b>/var/www/html/stgapi/vendo
r/zendframework/zendframework/library/Zend/Http/Header/Origin.php</b> on line <b
>36</b><br />

**Comment by fabiopaiva** [comment]
+1
PHP Fatal error:  Uncaught exception 'Zend\\Http\\Header\\Exception\\InvalidArgumentException' with message 'Invalid header value for Origin key: "Origin"'

**Comment by Cyruxx** [comment]
That's because your Origin Header has the value ´file://´.

**Comment by fabiopaiva** [comment]
@Cyruxx  yes
https://github.com/zf-fr/zfr-cors/issues/18

**Comment by sohailyasmin** [comment]
how to resolve this ?

**Comment by Cyruxx** [comment]
As mentioned by @fabiopaiva in #18 there's a workaround for this:


    
    public function onBootstrap(MvcEvent $e)
    {
        $eventManager        = $e->getApplication()->getEventManager();
        $headers = $e->getRequest()->getHeaders();
        if ($headers->has('Origin') &&
            $headers->has('X-Requested-With') &&
            $headers->get('X-Requested-With')->getFieldValue() === 'com.domainname.mycordovapackagename') {
            //convert to array because get method throw an exception
            $headersArray = $headers->toArray();
            $origin = $headersArray['Origin'];
            if ($origin === 'file://') {
                unset($headersArray['Origin']);
                $headers->clearHeaders();
                $headers->addHeaders($headersArray);
                //this is a valid uri
                $headers->addHeaderLine('Origin', 'file://mobile');
            }
        }
    }
    
in zfr-cors.local.php add
    
    return array(
        'zfr_cors' => array(
         /**
          * Set the list of allowed origins domain with protocol.
          */
        'allowed_origins' => array(
            'file://mobile',
        )
        //...//
    );

**Comment by solcre** [comment]
Thank god someone posted about this, It was killing me! So much time lost today because of this.

**Comment by devit** [comment]
+1 thanks for the posted fix

**Comment by fabiopaiva** [comment]
@bakura10 this is a duplicate from #18, please close this too
