### ISSUE TITLE
Cross domain error on some API service only

### ISSUE THREAD

**Issue by ludal74** [zf-fr/zfr-cors#32]
Hi !

Firstable, thank you for your contribution, a lot of your ZF2 modules are realy excellent, usefull, and timesavers.

I'm working on an API using APIGILITY, and I use your module Zfrcors, but the check only works for some services in the API not all.

Did I miss something in the configuration ? (per AAPI config key, or per service config key ?).

Thanks in advance

Ludovic

**Comment by Cyruxx** [comment]
That's actually hard to say without any information about what exactly your configs look like.

**Comment by ludal74** [comment]
My fault. I had a PHP warning and the service returned a not allowed error response (that's the reason I didn't understood the error message).

All works great now.

Thanks again fir all the job you share
