### ISSUE TITLE
Dynamic allowed_origins / further configuration

### ISSUE THREAD

**Issue by danbroooks** [zf-fr/zfr-cors#33]
I would like to use this plugin, but instead of setting `allowed_origins` to `*` I'd like to provide a list of domains dynamically (ie via list of domains pulled from a database). 

I took a brief look at the code and noticed that the `CorsOptions` object is configurable, but is encapsulated in `CorsService`. I've used Zend before but I'm new to ZF2, and not sure where to go from here to replace the `CorsService`, or if it's even possible.

Is it possible to achieve dynamic configurations in the way I outline above? and if not is it something you would consider a PR for?

**Comment by boesing** [comment]
I know this issue is quite old but with zf2 you can create [Delegator Factories](https://ocramius.github.io/blog/zend-framework-2-delegator-factories-explained/).

In this case, you could create a delegator which queries your database for the origins and inject them by using `CorsOptions::setAllowedOrigins` from within the `Delegator Factory`.

**Comment by ddelrio1986** [comment]
@danbroooks you can use a delegator factory for this like @boesing said. Thanks for the tip @boesing. I never used a delegator factory before and now I know what they are and how to use them. I just created one that altered the way the CorsOptions object is populated. I'm not using a database but instead allowing different CORS headers based on the route.

**Comment by ddelrio1986** [comment]
I think this issue can be closed. I am still using delegator factories in ZF3 apps to do this.

**Comment by boesing** [comment]
@ddelrio1986 I guess that this is the most elegant way either.
Even if there would be a `ConfigurationProvider`, you still had to create the database connection yourself and just moving your stuff from your delegator to the provider.

@weierophinney Would you mind closing this?
