### ISSUE TITLE
Error with ionic/cordova application

### ISSUE THREAD

**Issue by coolmic** [zf-fr/zfr-cors#34]
I am developing a web service, accessible from an web-app, and from mobile devices (applications build with cordova/ionic).

When an application for android/ios build with ionic make an ajax request with method POST, it send this header :  `Origin: file://` 
(And there is no preflight, because it's an app)
With ZfrCors module, I am getting a empty body with statusCode = 200

The issue lies within this line : https://github.com/coolmic/zfr-cors/blob/master/src/ZfrCors/Service/CorsService.php#L65

`file://` is not a valid uri, so it throws exception, and quietly failing without error.
I wanted to make a pull request to fixed it, but I noticed the problem lies elsewhere too ( https://github.com/zendframework/zend-http/blob/master/src/Header/Origin.php#L34 ).

What should we do? 
According to the rfc (https://tools.ietf.org/html/rfc6454#page-13) , origin must be indeed an valid uri.

```
origin= "Origin:" OWS origin-list-or-null OWS
origin-list-or-null = %x6E %x75 %x6C %x6C / origin-list
origin-list         = serialized-origin *( SP serialized-origin )
serialized-origin   = scheme "://" host [ ":" port ]
                       ; <scheme>, <host>, <port> from RFC 3986
```

So ionic is in the wrong, but I guess there is little chance they will fixed it.

See http://blog.ionic.io/handling-cors-issues-in-ionic/#runningonadevice

Should we fix this module? Or should I resolve myself to add

``` php
if (isset($_SERVER['HTTP_ORIGIN']) && $_SERVER['HTTP_ORIGIN'] === 'file://') {
    $_SERVER['HTTP_ORIGIN'] = null;
}
```

in public/index.php as a workaround ?

**Comment by gsomoza** [comment]
Did you try adding the following to the server (its in the project's README): 
`UriFactory::registerScheme('file', 'Zend\Uri\Uri');`

Otherwise I'd do what you suggested at the end, possibly also adding a conditional so that it only works on certain environments (e.g. local / dev).

FYI I'm not on this project - just happened to run into a similar issue and this worked for me (I was using Postman, which is a Chrome extension).
