### ISSUE TITLE
Uncaught Exception ZfrCors\Exception\InvalidOriginException

### ISSUE THREAD

**Issue by boesing** [zf-fr/zfr-cors#48]
Using v1.4.0

```
Uncaught Exception ZfrCors\Exception\InvalidOriginException: "Provided header value supposed to be invalid." at vendor/zfr/zfr-cors/src/ZfrCors/Exception/InvalidOriginException.php line 18
```

Stacktrace:
```
#0 vendor/zfr/zfr-cors/src/ZfrCors/Service/CorsService.php:70
#1 vendor/zfr/zfr-cors/src/ZfrCors/Mvc/CorsRequestListener.php:134
#2 {"function":"onCorsRequest","class":"ZfrCors\Mvc\CorsRequestListener","type":"->","args":["[object] (Zend\Mvc\MvcEvent: {})"]}
#3 vendor/zendframework/zend-eventmanager/src/EventManager.php:490
#4 vendor/zendframework/zend-eventmanager/src/EventManager.php:214
#5 index.php:58
```

**Comment by boesing** [comment]
Do I need to bump this? 
We should consider to provide a hotfix for this bug, don't we?

**Comment by bakura10** [comment]
Hi !

I no longer maintain this package, sorry. Maybe @weierophinney can help as zfr-cors is used within Apigiliy?

**Comment by boesing** [comment]
If no one wants to maintain this package, I can help out until someone else is found.
I am available in ZF slack if you want to notify me about this.

**Comment by amahrt** [comment]
@bakura10 I can also help you guys out.

**Comment by ddelrio1986** [comment]
@bakura10 I would be willing to help out as well. I use this in a ton of important applications.

**Comment by bakura10** [comment]
Awesome guys ! Unfortunately as this is an important package used by Apigility I can't obviously give that kidn of permissions, however feel free to submit pull requests that contain fixes to known issue. I will try to find some time (or @weierophinney ?) to try to review them.

Thanks a lot :)

**Comment by weierophinney** [comment]
@boesing The line that is causing the exception is one raised when an exception is caught when pulling the `Origin` header from the request.

There is exactly one reason that can happen: if the URI present in the Origin header is invalid.

Can you check that, and report back if changing it solves the issue, and/or if you cannot figure out why it's invalid?

**Comment by boesing** [comment]
@weierophinney Thats exactly the case. A Request with an invalid Origin does throw an `InvalidOriginException` within `CorsService::isCorsRequest`.

The `CorsRequestListener::onCorsPreflight` is catching that exception and returns a response with status `400` as expected.
After this, the `Mvc` workflow continues and the `MvcEvent::EVENT_FINISH` is being triggered, which will trigger the `CorsRequestListener::onCorsRequest` Method.

There is another `CorsService::isCorsRequest`, which will, of course, throw the `InvalidOriginException` again. But in this case, its not being catched and there will be an unhandled exception.

Thats why I've created the PR #47.
