### ISSUE TITLE
Not work for POST method =/

### ISSUE THREAD

**Issue by arenasam** [zf-fr/zfr-cors#51]
In GET request its work fine! 

my zf_cors.global.php
```
`return array(
    'zfr_cors' => array(
         'allowed_origins' => array('http://localhost:4200'),
         'allowed_methods' => array('GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'),
          'allowed_headers' => array('Authorization'),
    ),
);`

```
My .htaccess

```
`RewriteEngine On
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteRule !\.(js|gif|jpg|png|css|txt)$ public/index.php [L]
RewriteCond %{REQUEST_URI} !^/public/
RewriteRule ^(.*)$ public/$1 [NC,L]
`
```

I using AbstractActionController

Any sugestion? thx

**Comment by ddelrio1986** [comment]
What is the error encountered? Are you able to provide the headers for the POST request?

**Comment by arenasam** [comment]
im resolved, 

in cliente: 
let header = new HttpHeaders({'Content-type': 'multipart/form-data'});
return this.http.post<User>(`${MEAT_API}/login`, {email: email, password: password}, {headers: header});

in Zf2: json_decode($this->getRequest()->getContent());
